-- Run this while connected to the schema user you created in Oracle XE 21c.
-- Tables are in 3NF: master data is separate; ENROLLMENTS resolves the many-to-many relation;
-- ATTENDANCE records one status for one enrollment on one day.
CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR2(30) NOT NULL UNIQUE,
    full_name VARCHAR2(120) NOT NULL,
    email VARCHAR2(160) NOT NULL UNIQUE
);
CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR2(30) NOT NULL UNIQUE,
    course_name VARCHAR2(120) NOT NULL,
    description VARCHAR2(500)
);
CREATE TABLE enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL REFERENCES students(student_id),
    course_id NUMBER NOT NULL REFERENCES courses(course_id),
    CONSTRAINT uq_enrollment UNIQUE (student_id, course_id)
);
CREATE TABLE attendance (
    attendance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER NOT NULL REFERENCES enrollments(enrollment_id),
    attendance_date DATE NOT NULL,
    status VARCHAR2(10) NOT NULL,
    CONSTRAINT ck_attendance_status CHECK (status IN ('PRESENT', 'ABSENT')),
    CONSTRAINT uq_attendance_day UNIQUE (enrollment_id, attendance_date)
);
