package com.attendance.dao;

import com.attendance.model.*;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;

public class AttendanceDAO {
    public void markAttendance(int enrollmentId, LocalDate date, boolean present, int teacherId) {
        String sql="MERGE INTO attendance a USING (SELECT ? enrollment_id, ? attendance_date FROM dual) source ON (a.enrollment_id=source.enrollment_id AND a.attendance_date=source.attendance_date) WHEN MATCHED THEN UPDATE SET status=? WHEN NOT MATCHED THEN INSERT (enrollment_id,attendance_date,status) VALUES (source.enrollment_id,source.attendance_date,?)";
        String ownership="SELECT 1 FROM enrollments e JOIN courses c ON c.course_id=e.course_id WHERE e.enrollment_id=? AND c.teacher_id=?";
        try(Connection c=DatabaseManager.getConnection();PreparedStatement check=c.prepareStatement(ownership);PreparedStatement p=c.prepareStatement(sql)){check.setInt(1,enrollmentId);check.setInt(2,teacherId);try(ResultSet rs=check.executeQuery()){if(!rs.next())throw new IllegalArgumentException("Attendance access denied.");}p.setInt(1,enrollmentId);p.setDate(2,java.sql.Date.valueOf(date));String status=present?"PRESENT":"ABSENT";p.setString(3,status);p.setString(4,status);p.executeUpdate();}catch(SQLException ex){throw new DataAccessException("Unable to save attendance.",ex);}
    }
    public Map<Integer,Boolean> getAttendanceByDateAndCourse(LocalDate date,int courseId,int teacherId){Map<Integer,Boolean> result=new HashMap<>();String sql="SELECT e.student_id,a.status FROM enrollments e JOIN courses c ON c.course_id=e.course_id LEFT JOIN attendance a ON a.enrollment_id=e.enrollment_id AND a.attendance_date=? WHERE e.course_id=? AND c.teacher_id=?";try(Connection c=DatabaseManager.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setDate(1,java.sql.Date.valueOf(date));p.setInt(2,courseId);p.setInt(3,teacherId);try(ResultSet rs=p.executeQuery()){while(rs.next())result.put(rs.getInt(1),"PRESENT".equals(rs.getString(2)));}}catch(SQLException ex){throw new DataAccessException("Unable to load attendance.",ex);}return result;}
    public List<StudentAttendanceReport> getStudentAttendanceReport(String searchName,Integer courseId,int teacherId){List<StudentAttendanceReport> rows=new ArrayList<>();String sql="SELECT s.student_code,s.full_name,c.course_name,SUM(CASE WHEN a.status='PRESENT' THEN 1 ELSE 0 END),COUNT(a.attendance_id) FROM enrollments e JOIN students s ON s.student_id=e.student_id JOIN courses c ON c.course_id=e.course_id LEFT JOIN attendance a ON a.enrollment_id=e.enrollment_id WHERE c.teacher_id=? AND (LOWER(s.full_name) LIKE ? OR LOWER(s.student_code) LIKE ?) AND (? IS NULL OR c.course_id=?) GROUP BY s.student_code,s.full_name,c.course_name ORDER BY s.full_name";String like="%"+(searchName==null?"":searchName.trim().toLowerCase())+"%";try(Connection c=DatabaseManager.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setInt(1,teacherId);p.setString(2,like);p.setString(3,like);if(courseId==null){p.setNull(4,Types.INTEGER);p.setNull(5,Types.INTEGER);}else{p.setInt(4,courseId);p.setInt(5,courseId);}try(ResultSet rs=p.executeQuery()){while(rs.next()){long present=rs.getLong(4),total=rs.getLong(5);rows.add(new StudentAttendanceReport(rs.getString(1),rs.getString(2),rs.getString(3),present,total,total==0?0:present*100.0/total));}}}catch(SQLException ex){throw new DataAccessException("Unable to create attendance report.",ex);}return rows;}
}
